// Generated by `nuxt prepare` (postinstall): .nuxt/eslint.config.mjs
// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    ignores: [
      'public/**',
      '.data/**',
      '.output/**',
      '**/prisma/migrations/**',
      'generated/**',
    ],
  },
  {
    rules: {
      // Tighten the codebase gradually; warn instead of blocking CI
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
)
